/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:5de29c20-7396-43d9-b2d2-80f379831a94",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_rrL6GQKFV",
    "aws_user_pools_web_client_id": "3lbpn2otpnd60piqe988t9ias6",
    "oauth": {}
};


export default awsmobile;
